### ISSUE TITLE
Rename filestat_get to just stat_get?

### ISSUE THREAD

**Issue by caspervonb** [WebAssembly/wasi-filesystem#1]
Bikeshedding here, but as the module names have become more specialised it may make sense to rename filestat_get to just stat_get.

**Comment by sunfishcode** [comment]
The modular names and modularization are still being figured out, but once that's done, I agree that something something like this will make sense.

**Comment by sunfishcode** [comment]
It is now named `stat-at`, which is nice and concise, and close to POSIX.
