### ISSUE TITLE
bad link in description of directory-entry-stream

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/wasi-filesystem#107]
https://github.com/WebAssembly/WASI/blob/main/docs/WitInWasi.md#Streams is a bad link, and I'm not sure the substitute https://github.com/WebAssembly/wasi-filesystem/blob/main/wit/filesystem.wit#L757-L760

**Comment by sunfishcode** [comment]
I apologize for things getting out of sync. The link depends on https://github.com/WebAssembly/WASI/pull/517. Temporarily, you can view it [here](https://github.com/WebAssembly/WASI/blob/d071b59a440be61a9b2d38e3778f184fbab95f4b/docs/WitInWasi.md#streams).

**Comment by sunfishcode** [comment]
https://github.com/WebAssembly/WASI/pull/517 is now merged, so the link now works.
