### ISSUE TITLE
Clarify fd_seek behaviour for out-of-bounds access

### ISSUE THREAD

**Issue by RReverser** [WebAssembly/wasi-filesystem#13]
`fd_seek` states that it's "similar to lseek".

However, the latter has some... interesting behaviour in regards to holes and random seek that 1) depends on the provided flags and 2) might be complicated to replicate across all platforms.

It would be helpful if the API docs would explicitly state whether out-of-bounds seeking is permitted and, if so, what is expected when it happens.

P.S. This is somewhat related to WebAssembly/WASI#9 which I hope will cover such edge-cases.

**Comment by sunfishcode** [comment]
I submitted #77 to propose that we guarantee that the bytes are zeroed.
