### ISSUE TITLE
Eliminte ctim field?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-filesystem#18]
WASI's filestat struct contains this `ctim` field:
```
;;; Last file status change timestamp.
    (field $ctim $timestamp)
```
This is a POSIX field, however this information is not available on Windows, and it isn't broadly useful. It only reflects events like `chmod`, `chown`, or `link`.

This is not to be confused with the creation time, which isn't in Posix, but is in Windows, macOS, Linux, and other popular systems, and which is something we may want to add to WASI.

A possible plan here might be:
 - Eliminate the `ctim` field.
 - Specify that the `mtim` field reflects the most recent modification *or* status change where applicable, which should hopefully allow programs that need to detect changes to notice that something changed.

**Comment by piscisaureus** [comment]
> however this information is not available on Windows

It is available in Windows though.
See the `ChangeTime` field [here](https://docs.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-file_basic_info).

**Comment by sunfishcode** [comment]
Ah, it appears I was mistaken here. Thanks!
