### ISSUE TITLE
How does `fs_rights_inheriting` work in `path_open`?

### ISSUE THREAD

**Issue by yagehu** [WebAssembly/wasi-filesystem#23]
Comment for [`fs_rights_inheriting`](https://github.com/WebAssembly/WASI/blob/a206794fea66118945a520f6e0af3754cc51860b/phases/ephemeral/witx/wasi_ephemeral_path.witx#L118) says:

```
    ;;; The *base* rights are rights that will apply to operations using the file
    ;;; descriptor itself, while the *inheriting* rights are rights that apply to
    ;;; file descriptors derived from it.
```

What does "derived" mean in this context? Examples would be super helpful.

**Comment by sunfishcode** [comment]
#31 will remove the rights system, obviating this.
