### ISSUE TITLE
Clarifying rights::path_filestat_set_size

### ISSUE THREAD

**Issue by MaulingMonkey** [WebAssembly/wasi-filesystem#28]
[`rights::path_filestat_set_size`]'s definition seems fairly ambiguous to me - the current wording is extremely general, "The right to change a file's size.", but then it *only* describes it's interaction with [`open`].  I can't tell if it's meant to:

1. apply broadly to a bunch of syscalls ([`allocate`], [`filestat_set_size`], [`pwrite`]/[`write`] if extending the file size), or some subset of those, and if so - if it implies, or is implied by, or is required in tandem with related sizing rights that control those syscalls ([`rights::fd_allocate`], [`rights::fd_filestat_set_size`])

or perhaps, at the other extreme:

2. apply *only* to truncation via [`open`], with the original naming being just to match POSIX.

[`allocate`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#allocate
[`filestat_set_size`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#filestat_set_size
[`read`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#read
[`open`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#open
[`pwrite`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#pwrite
[`write`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#write

[`rights::fd_allocate`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#rights.fd_allocate
[`rights::fd_filestat_set_size`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#rights.fd_filestat_set_size
[`rights::path_filestat_set_size`]:https://github.com/WebAssembly/WASI/blob/3d47b13268e8c88dcead167ffb41013482f04cf8/phases/ephemeral/docs.md#rights.path_filestat_set_size

**Comment by MaulingMonkey** [comment]
Fair enough!  It's certainly dead weight for my own use cases.

While someone may want permission APIs for the filesystem in the future - perhaps OpenBSD style `pledge` / `unveil` - said APIs can always be added later, if/when there are actual motivating use cases and codebases that will take advantage of said APIs.

**Comment by sunfishcode** [comment]
#31, removing the rights system, is the path forward here.
