### ISSUE TITLE
Add a more general __WASI_FILETYPE_SOCKET

### ISSUE THREAD

**Issue by kubkon** [WebAssembly/wasi-filesystem#4]
Currently, we have `__WASI_FILETYPE_SOCKET_STREAM` and `__WASI_FILETYPE_SOCKET_DGRAM` which seems to be a tad bit too specfic for calls such as `fd_readdir`. That is, when translating `libc::dirent` to `__wasi_dirent_t`, we are required to do custom mapping between `libc::dirent::d_type` to `__wasi_dirent_t::__wasi_filetype_t`, and it becomes convoluted and tricky to properly work out whether we are dealing with a socket stream or datagram. Why is that? Note that when performing an `fd_readdir` call in WASI, we pass in a descriptor to the directory only; we then receive `libc::dirent` structures one by one, and perform translation to `__wasi_dirent_t`. If the underlying "file" is a socket, we have no way of working out whether it's a stream or datagram without performing another syscall, i.e., `getsockopt` (`libc::dirent::d_type` only tells us that we're dealing with *some* sort of a socket).

My proposition here would be to create a more general WASI filetype, `__WASI_FILETYPE_SOCKET`, which would act as a catch-all for all socket types, and we would then burden the WASI client to actually perform another syscall to work out what type of socket they are actually dealing with.

**Comment by linclark** [comment]
[bookkeeping] Added to the [Moving wasi-filesystem to Phase 3](https://github.com/WebAssembly/WASI/projects/2) project.

**Comment by sunfishcode** [comment]
The current wasi-filesystem.wit.md now contains a `socket` in the `type` enum.
