### ISSUE TITLE
Add a link in the README to the location or status of the witx file

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/wasi-filesystem#46]
Hi, I understand folks are already building with this component, just I'm not sure how. I may be missing something, but I would expect a witx file as that would have for example, the component's module name used for imports, right?

Please let me know if I'm misunderstanding something, but for example crypto makes sense to me as there are witx source there... I'm hazy on the translation of markdown (which exists here) without the witx file (which doesn't exist here, or maybe exists somewhere else?)

https://github.com/WebAssembly/wasi-crypto/tree/main/witx

**Comment by sunfishcode** [comment]
This wasi-filesystem proposal has migrated to the new wit format. Not all proposals have migrated yet, as we are still going though a transition process.

The interface description is in [wasi-filesystem.wit.md](https://github.com/WebAssembly/wasi-filesystem/blob/main/wasi-filesystem.wit.md), which is a markdown file containing `wit` code blocks. The `wit` code blocks are conceptually extracted and concatenated to form the actual `wit` source code.

Currently, in the wit format, the module name is derived from the wit source file name. For wasi-filesystem.wit.md, the module name is "wasi-filesystem".

**Comment by codefromthecrypt** [comment]
cool thanks for explaining!
