### ISSUE TITLE
Define a preopen resource and update relevant wit APIs to define subtypes of it.

### ISSUE THREAD

**Issue by kulakowski-wasm** [WebAssembly/wasi-filesystem#50]

**Comment by kulakowski-wasm** [comment]
We've decided to move forward with a different strategy for preview2 that does not require resource subtyping at this time.

This new plan will be part of @sunfishcode 's presentation at the October 6 WASI meeting, so stay tuned!

**Comment by codefromthecrypt** [comment]
Is there any summary on what replaces preopens in preview2? Or do we expect them to not exist? wazero is trying to structure its code and docs forward compatibly, and points like these make it difficult (e.g. pre-opens not associated in the filesystem module)

**Comment by sunfishcode** [comment]
I've now added a world sketch to https://github.com/WebAssembly/WASI/issues/509 which includes a preopens argument to main, which is a list of pairs of handles and names, which is roughly the same as preopens in preview1 except with the generalization to more resource types.

**Comment by codefromthecrypt** [comment]
I think I understand now. Effectively there will no longer be a need for functions to get preopen info because these are now parameters to `command`. Thanks!
