### ISSUE TITLE
Home directory

### ISSUE THREAD

**Issue by HKalbasi** [WebAssembly/wasi-filesystem#59]
For porting applications that rely on home directory concept, is a standard choice or function to use? If not, is it fine to use `$HOME` environment variable which unix usually sets? Asking for adding WASI version of `home_dir` function in [`home`](https://github.com/brson/home) rust crate.

**Comment by sunfishcode** [comment]
The idea that all Rust code runs within an environment that has a concept of a "user account" that exists on a "system" which has a "home directory" with certain expected contents and expectations, is not one that cleanly maps to WASI's approach to sandboxing and virtualization.

Typically, when people ask how to get the home directory on WASI, we ask what they're going to use it for, and then with that extra context, we're often able to give them more specific advice on what to do. The `home` operates at a level of abstraction which doesn't permit us to ask these more specific questions. So I don't yet know what to say here.

**Comment by HKalbasi** [comment]
> Typically, when people ask how to get the home directory on WASI, we ask what they're going to use it for, and then with that extra context, we're often able to give them more specific advice on what to do.

What are possible solutions? Maybe we can find a common thing in them.

I think when programs need home, they need an isolated place to persist some files and configs, without conflicts with other users running the same program. In WASI file system is usually isolated more than scope of a user, and I think any path is a valid path in this case. By using `$HOME` and `/` if it wasn't available in env, it will compile and work in most cases (because it doesn't matter what it is) and if they want simulate a multi user scenario, they can provide `$HOME`. And even if it isn't what they need and they want more control (is there any?), they can drop `home` and use something else, which is what they should do today since it doesn't compile on WASI.

**Comment by sunfishcode** [comment]
My suggestion would be to have `home_dir` return `None`, for now. That way, we don't need to block you here, and an implementation can be added later if we figure out what it should do.

Are two different WASI programs running as the same user or different users? They are sandboxed from each other within WASI, but should they share a "home" directory? There may be situations where one wants that, and situations where one doesn't. Until we have a more complete answer, I think it's best to be conservative here.

**Comment by sunfishcode** [comment]
The original question here seems answered; please reopen if there are any further questions!

**Comment by HKalbasi** [comment]
> Are two different WASI programs running as the same user or different users? They are sandboxed from each other within WASI, but should they share a "home" directory? There may be situations where one wants that, and situations where one doesn't. Until we have a more complete answer, I think it's best to be conservative here.

I still don't see how this has conflict with returning $HOME? By returning the `$HOME` as the home directory it allows for flexibility for the user to decide whether they want the programs to share a home directory or not. If the user wants the programs to share a home directory, they can set the $HOME environment variable to the same value for both programs. If the user wants the programs to have different home directories, they can set the $HOME environment variable to different values for each program. And if the user wants the home directory to be unspecified, they can choose not to provide a $HOME environment variable. And if wasi some day wants to add something like `getpwuid_r` (which probably doesn't want ever) it still should provide some env variable similar to windows and unix to override it.
